import turtle

#Dice1 drawing 
def dice1():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(50, 50)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()

#Dice2 drawing  
def dice2():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(30, 50)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(70, 50)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()

#Dice3 drawing  
def dice3():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(30, 30)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(50, 50)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(70, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()

#Dice4 drawing  
def dice4():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(20, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(80, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(20, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(80, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()

#Dice5 drawing  
def dice5():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(50, 50)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(20, 80)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(80, 80)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(22, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(80, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()

#Dice6 drawing  
def dice6():
  turtle.reset()
  turtle.pendown()
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.left(90)
  turtle.forward(100)
  turtle.penup()
  turtle.goto(20, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(45, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(75, 70)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(45, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(20, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.penup()
  turtle.goto(75, 20)
  turtle.pendown()
  turtle.color("black")
  turtle.dot(10)
  turtle.hideturtle()
